### PR TITLE
Bump version to 2.1.1

### PR DESCRIPTION
**Pull request by notriddle**

### CODE REVIEW

**Comment by notriddle** [comment]
@aelita-mergebot r+

**Comment by ghost** [comment]
:-1: [Build failed](https://travis-ci.org/notriddle/quickersort/builds/167732785)

**Comment by notriddle** [comment]
I fixed another problem.

@aelita-mergebot r+

**Comment by ghost** [comment]
:+1: [Build succeeded](https://travis-ci.org/notriddle/quickersort/builds/167733705)

**Pull request merged**
