### PR TITLE
Add deprecation notice

### LINKED ISSUE #27: Compare performance to std::sort_unstable
It seems like we are not really faster anymore for large vectors when comparing to `std::sort_unstable`: https://gist.github.com/vks/e56cb2a0702765c66c0ccbf1abb8b5b4

We should probably reword the readme accordingly and update the benchmark results.

### PR DESCRIPTION
**Pull request by notriddle**
Closes #27

### CODE REVIEW

**Comment by vks** [comment]
What about `sort_floats`? I think it could be moved to its own crate and survive `quickersort`.

**Comment by vks** [comment]
r+

I would suggest to add
```toml
[badges]
maintenance = { status = "deprecated" }
```
to the `Cargo.toml` and release a new version.

**Comment by notriddle** [comment]
> What about sort_floats? I think it could be moved to its own crate and survive quickersort.

[It already is](https://github.com/notriddle/rust-float-ord/)

**Comment by vks** [comment]
Oh, nice, I did not find it when searching for `sort float`. I opened a PR adding keywords to fix this.

**Pull request merged**
